### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by nathalie1226** [pratity4samutpada/BuzzQuiz#2]
those lines of code are repeated a few times : " switchQuestion();
    interrogate();
    setTimeout(generateQuestion, 3000);"
you could refactor and put them in a function that you just call every time
so many things you can do to refactor the code especially in the function generateQuestion() try to go over it and refactor

**Comment by pratity4samutpada** [comment]
Refactored code in the places you mentioned. Definitely something I need to work on. Thanks!
